### ISSUE TITLE
Allowing awardCriteria in Tender?

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting-extensions/ocds_awardCriteriaBreakdown_extension#3]
Both TED and eForms apply award criteria at lot level.

However, there may non-EU cases where a procedure is not allotted and the data publisher doesn't want to use the "virtual" lot approach*. For these cases, supporting the attachment of awardCriteria to `Tender` could be relevant.

**\*** The creation of a single `Lot` object in `tender.lots` to have certain properties only in `tender.lots`, and not in `tender`, regardless of the existence of lots in the procurement procedure

**Comment by ColinMaudry** [comment]
See also : https://github.com/open-contracting/standard/issues/891

**Comment by jpmckinney** [comment]
open-contracting/standard#891 is to discuss whether publishers will need to use lots, whether they like it or not. I describe what the concept of 'Lot' is intended to mean in OCDS in a couple comments here: https://github.com/open-contracting/standard/issues/888#issuecomment-516972841 It's not meant to only match 'real' lots.

For this issue, I prefer to only extend Lot until we have a real demand to extend Tender.
